In [1]:
# Given the following python code, what would the output of the code give ?
my_tuppy = (1,2,5,8)
my_tuppy[2] = 6
# The ouput gave a type error

TypeError: 'tuple' object does not support item assignment

Question 2: Which of the following python codes can be used to access data across rows and columns

- Answer: df.loc() and df.iloc()![Question 9.png]()

In [2]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Reading the data
df = pd.read_csv("StageA_data.csv",encoding = "latin_1")
df.head() # displays the first 5 rows

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

Question 3 : What is the total protein supply in Madagascar in 2015?

In [4]:
new_df = df[['Element','Area','Y2015']]
new_grouped_df = new_df.groupby(['Element','Area']).sum()
new_grouped_df
m_protein_supply_2015 = new_grouped_df.loc[('Protein supply quantity (g/capita/day)', 'Madagascar')]
print("The total Protein supply in Madagascar in 2015 is:",m_protein_supply_2015)

The total Protein supply in Madagascar in 2015 is: Y2015    173.05
Name: (Protein supply quantity (g/capita/day), Madagascar), dtype: float64

Question 4 : A pandas dataframe with dimensions (100,3) has how many features and observations ?

- Answer : 100 Observations and 3 Features

In [5]:
# Question 5 : # What would be the output for S[0][1][1]?
S = [['him', 'sell'], [90, 28, 43]]
S[0][1][1]

'e'

In [6]:
# Given the following numpy array
array  = ([[94, 89, 63],

             [93, 92, 48],

             [92, 94, 56]])
# How would you select  the elements in bold and italics from the array?
array

[[94, 89, 63], [93, 92, 48], [92, 94, 56]]

Question 6: Which of the following is a python built in module ?
- Seaborn
- Math
- Matplotlib
- Pandas

- Answer : ALL OF THE ABOVE

In [7]:
# Question 7: Perform a groupby operation on Element , which year has the highest sum of Stock Variation ?
grouped_by_element = df.groupby("Element").sum(numeric_only= True)
row_sv = grouped_by_element.loc["Stock Variation"]
print(row_sv)
print("The year with the highest Stock Variation is 2014")

Area Code         571566.00
Item Code       11329527.00
Element Code    21464704.00
Y2014              58749.83
Y2015              34910.99
Y2016              33140.12
Y2017              54316.91
Y2018              20577.91
Name: Stock Variation, dtype: float64
The year with the highest Stock Variation is 2014

Question 8 : Which of these python Data structures is unorderly ?

- List
- Tuple
- Dictionary
- Set

- Answer : Dictionary and Set

![Question 9.png]()

In [8]:
# Question 10 : Select the columns 'Area' and '2017'. Perform a groupby operation on 'Area'. Which of these areas has the highest sum in 2017
new_columns = df[['Area','Y2017']]
area_sum = new_columns.groupby("Area").sum()
area_sum_sorted = area_sum.sort_values(by = 'Y2017', ascending = False)
print(area_sum_sorted)
print("Nigeria has the highest sum in 2017")

                                  Y2017
Area
Nigeria                      1483268.23
Egypt                         866379.92
South Africa                  517590.54
Ethiopia                      448683.76
Morocco                       388495.36
Ghana                         337599.06
Algeria                       325644.27
United Republic of Tanzania   322616.85
Kenya                         264660.66
Sudan                         239931.92
Cameroon                      232030.43
Angola                        229159.57
Côte d'Ivoire                 224599.01
Uganda                        213950.38
Malawi                        181098.71
Mozambique                    161407.98
Mauritania                    156665.46
Mali                          149928.33
Madagascar                    131197.73
Niger                         126707.58
Benin                         124771.22
Tunisia                       124167.20
Zambia                        103223.77
Burkina Faso                  101855.07
Guinea                         98138.87
Senegal                        95681.15
Zimbabwe                       75919.34
Rwanda                         73663.69
Chad                           71594.68
Sierra Leone                   55311.33
Eswatini                       54343.33
Mauritius                      51114.83
Togo                           49841.88
Congo                          41181.68
Central African Republic       29937.00
Namibia                        29874.89
Liberia                        29342.20
Gabon                          27979.64
Gambia                         23154.18
Djibouti                       22729.91
Botswana                       22101.30
Lesotho                        21267.96
Guinea-Bissau                  19102.77
Cabo Verde                     14650.74
Sao Tome and Principe          12662.63
Seychelles                       442.34
Comoros                           59.84
Sudan (former)                     0.00
Ethiopia PDR                       0.00
Nigeria has the highest sum in 2017

In [9]:
# Question 11 :  Consider the following list of tuples:
y = [(2, 4), (7, 8), (1, 5, 9)]
# How would you assign element 8 from list to variable x
y[1][1]
# x  would be equal to y[1][1]

8

Question 12 : How would you check for the number of rows and column in a pandas dataframe named df ?
- pd.length(df)
- df.shape
- len(df)
- df.shape()


- Answer : df.shape

In [10]:
# Question 13 : What is the mean and Standard Devaition across the whole dataset for the year 2017 in 2 decimal places
df.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [11]:
# Question 14 : What is the total number and percentage of missing values in 2014 to 3 decimal places ?
tot_rows = df.shape
tot_null_rows = df['Y2014'].isna().sum()
percentage_of_null_values = (tot_null_rows/tot_rows)* 100
print(f"The number and percentage of missing values in 2014 are {tot_null_rows} and {percentage_of_null_values} respectively")

The number and percentage of missing values in 2014 are 1589 and [2.60735441e+00 1.32416667e+04] respectively

In [12]:
# Question 15 : Select the columns 'Area' and '2017'. Perform a groupby operation on 'Area'. Which of these areas has the 7th lowest sum in 2017 ?
area_sum_sorted.tail(7)

                          Y2017
Area
Guinea-Bissau          19102.77
Cabo Verde             14650.74
Sao Tome and Principe  12662.63
Seychelles               442.34
Comoros                   59.84
Sudan (former)             0.00
Ethiopia PDR               0.00

In [13]:
# Question 16 : What is the total sum of wine produced in 2015 ?
df.groupby('Item').sum(numeric_only=True)

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Item,,,,,,,,
"Alcohol, Non-Food",38447,752497,1515090,2403.00,2180.00,2223.00,2348.00,2293.00
Alcoholic Beverages,75016,1649136,2171381,102410.11,98783.72,96958.75,95581.06,97847.27
Animal Products,18060,397035,90990,11935.65,11811.73,11661.69,11547.65,11578.61
Animal fats,85279,1882494,2567303,209460.54,200675.72,183314.22,269617.53,269648.27
Apples and products,69280,1352989,1920418,9499.23,10559.15,9853.26,10198.90,9640.51
...,...,...,...,...,...,...,...,...
"Vegetables, Other",77779,1518715,2275409,155038.96,158104.08,156218.90,157752.59,163987.21
Vegetal Products,18060,391905,90990,107145.19,107064.17,106792.72,107655.20,107775.39
Wheat and products,87073,1639683,2654934,232670.13,234710.51,239377.07,240047.62,242645.19
Wine,66206,1319535,1818328,4497.36,4251.81,3872.09,4178.02,4039.32
Yams,50798,970905,1525745,200396.96,203151.78,220626.20,229174.59,221272.09

In [14]:
# Question 17 : What is the total number of unique countries in the dataset ?
total_unique_countries = new_columns['Area'].nunique()

print("Total number of unique countries in the dataset:", total_unique_countries)

Total number of unique countries in the dataset: 49

In [15]:
# Question 18 : Which year had the least correlation with Element Code ?
df.corr(numeric_only = True)

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Area Code,1.000000,-0.005159,-0.000209,0.006164,0.005472,0.005247,0.005006,0.005665
Item Code,-0.005159,1.000000,-0.024683,0.021722,0.020857,0.020109,0.021494,0.021314
Element Code,-0.000209,-0.024683,1.000000,0.024457,0.023889,0.023444,0.024254,0.024279
Y2014,0.006164,0.021722,0.024457,1.000000,0.994647,0.996081,0.995230,0.994872
Y2015,0.005472,0.020857,0.023889,0.994647,1.000000,0.995739,0.988048,0.988208
Y2016,0.005247,0.020109,0.023444,0.996081,0.995739,1.000000,0.992785,0.992757
Y2017,0.005006,0.021494,0.024254,0.995230,0.988048,0.992785,1.000000,0.998103
Y2018,0.005665,0.021314,0.024279,0.994872,0.988208,0.992757,0.998103,1.000000

In [16]:
# Question 19: Perform a groupby operation on Element , which year has the total number of the sum of processing in 2017 ?
df.groupby("Element").sum(numeric_only=True)

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,
Domestic supply quantity,708993,14197445,28068795,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,11840553,26026133,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,13535000,3435732,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,3538507,7282199,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,13285035,25406622,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,13511060,3329296,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,13185401,3163725,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,13795966,28834929,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,5424803,10292107,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,4729749,8926728,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,5350416,10313310,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,10450053,21388191,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,13535000,3385502,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,12421089,24066350,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,2035933,4211574,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,11329527,21464704,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,112545,22995,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,1486528,2869905,416.00,349.00,89.00,91.00,90.00

Question 20 : If you have the following list

lst = [[35, 'Portugal', 94], [33, 'Argentina', 93], [30 , 'Brazil', 92]]

col = ['Age','Nationality','Overall']

How do you create a pandas DataFrame using this list, to look like the table below?

![table.png]()

- pd.DataFrame(lst, columns = col, index = [i for i in range(1,4)])

- None of the above

- pd.Dateframe(lst, column = [‘Age’,’Nationality’,’Overall’], index = [1,2,3])

- pd.Dataframe(lst, columns = col, index = [1,2,3])

- pd.datframe(lst, column = [‘Age’,’Nationality’,’Overall’],index = [1,2,3])

- Answer : pd.DataFrame(lst, columns = col, index = [i for i in range(1,4)])